theme: jekyll-theme-minimal
title: MFV Petersberg e.V.
description: Modellflugverein in der NÃ¤he von Fulda
logo: logo.png

show_downloads: false

github:
  is_project_page: false
  is_user_page: false
